@startuml card_add_edit_dialog
title カード追加・編集ダイアログ

salt
{
  {T Add / Edit Card}
  名前        | [_____________________]
  レアリティ      | [________]
  セット         | [_____________________]
  コレクター番号 | [_____________________]
  効果      | {^ v} [ Select Effect ]
  メモ        |
              | {#
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                }
  [ Cancel ] | [ Save ]
}

@enduml

