@startuml
title デッキ使用（補完指示）ダイアログ

salt
{
  {以下を物理的に移動してください}
  {#table
    カード名 | 移動元 | 移動先 | 枚数 | メイン/サイド
    ------------------------------------------------
    {in}
    喉首狙い | 保管庫 | デッキ 1 | 1 | メイン
    悲嘆 | デッキ2 | デッキ 1 | 2 | サイド

  }
  {#table
    {out}
    カード名 | 移動元| 枚数 | メイン/サイド
    思考囲い | デッキ1 |1 | メイン
    思考囲い | デッキ1 |2 | サイド
  }
  [ 移動完了 ] | [  中止 ]
}

@enduml