name: cardpro
description: "新しいFlutterプロジェクトです。"
# この行は `flutter pub publish` を使って、このパッケージが誤って
# pub.dev に公開されるのを防ぎます。非公開パッケージにはこの設定が推奨されます。
publish_to: 'none' # 公開したい場合はこの行を削除してください。

# 以下の行は、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は「1.2.43」のように3つの数字で構成され、
# 必要に応じて「+」でビルド番号を追加できます。
# Flutterのビルド時に `--build-name` や `--build-number` で上書き可能です。
# Androidでは build-name は versionName、build-number は versionCode として使われます。
# 詳細：https://developer.android.com/studio/publish/versioning
# iOSでは build-name は CFBundleShortVersionString、build-number は CFBundleVersion に対応します。
# 詳細：https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windowsでは build-name がバージョン番号、build-number がビルド接尾辞として使われます。
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# dependencies セクションでは、このパッケージが動作するために必要な
# 他のパッケージ（ライブラリ）を指定します。
# `flutter pub upgrade --major-versions` を実行すると、依存関係を最新版に更新できます。
# また、下記のバージョン番号を手動で最新のものに変更することも可能です。
# どの依存パッケージに新しいバージョンがあるか確認するには、
# `flutter pub outdated` を実行してください。
dependencies:
  flutter:
    sdk: flutter

  # データベース（Drift）関連の依存パッケージ
  drift: ^2.15.0
  drift_sqflite: ^2.0.0
  path_provider: ^2.0.0
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.0 # ← これ必要！

  # Clean Architecture関連
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4

  # iOSスタイルのアイコン（Cupertino Icons）
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.15.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  bloc_test: ^9.1.5

  # flutter_lints は推奨されるコーディング規約（リント）を提供します。
  # 有効化はルートディレクトリの `analysis_options.yaml` で行います。
  # 特定のルールを無効化・追加したい場合はそちらを編集します。
  flutter_lints: ^5.0.0

# Dart の pubspec に関する情報の詳細はこちら：
# https://dart.dev/tools/pub/pubspec

# 以下は Flutter 特有の設定です。
flutter:

  # この行により、マテリアルアイコンフォントがアプリに含まれ、
  # Material Icons クラスを通じて使用できるようになります。
  uses-material-design: true

  # 画像などのアセットを追加するには、以下のように assets セクションを追加します：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # アセットに解像度ごとのバリエーションがある場合の指定方法：
  # https://flutter.dev/to/resolution-aware-images

  # パッケージに含まれるアセットを使用する場合の詳細はこちら：
  # https://flutter.dev/to/asset-from-package

  # カスタムフォントを追加するには、以下のように fonts セクションを追加します。
  # 各フォントには "family" 名と、"fonts" のリストでファイルとスタイルを指定します。
  # 例：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # パッケージ内のフォントの詳細はこちら：
  # https://flutter.dev/to/font-from-package
